// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYdCKuxmUY89Lk6YntvraXyff-2XR43sY',
    appId: '1:547677900481:web:4709e34ea814e2fa154e40',
    messagingSenderId: '547677900481',
    projectId: 'fir-kotlin-23c26',
    authDomain: 'fir-kotlin-23c26.firebaseapp.com',
    databaseURL: 'https://fir-kotlin-23c26-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kotlin-23c26.firebasestorage.app',
    measurementId: 'G-P31CJ4WWEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPMx3tbBXutDUDi64q96CXKQUcgYp1f8',
    appId: '1:547677900481:android:41c69adfda790dd6154e40',
    messagingSenderId: '547677900481',
    projectId: 'fir-kotlin-23c26',
    databaseURL: 'https://fir-kotlin-23c26-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kotlin-23c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoE8OF5BlB44oC7hbzhEhI8R-AuqbeTig',
    appId: '1:547677900481:ios:db06163cfd47b4aa154e40',
    messagingSenderId: '547677900481',
    projectId: 'fir-kotlin-23c26',
    databaseURL: 'https://fir-kotlin-23c26-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kotlin-23c26.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoE8OF5BlB44oC7hbzhEhI8R-AuqbeTig',
    appId: '1:547677900481:ios:db06163cfd47b4aa154e40',
    messagingSenderId: '547677900481',
    projectId: 'fir-kotlin-23c26',
    databaseURL: 'https://fir-kotlin-23c26-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kotlin-23c26.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYdCKuxmUY89Lk6YntvraXyff-2XR43sY',
    appId: '1:547677900481:web:ebfb7dc84c50a891154e40',
    messagingSenderId: '547677900481',
    projectId: 'fir-kotlin-23c26',
    authDomain: 'fir-kotlin-23c26.firebaseapp.com',
    databaseURL: 'https://fir-kotlin-23c26-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kotlin-23c26.firebasestorage.app',
    measurementId: 'G-JR43XG087X',
  );
}
